name: Client Production Deployment
env:
  WORKING_DIRECTORY: .
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    paths:
      - convex/**
      - src/**
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Deploy Project to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
